-- =============================================================================
-- 002_siem_schema.sql — SIEM tables (additive migration)
-- Owner: E1
-- Does NOT touch 001_init.sql tables (users, chats, messages)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- log_sources — configured log file paths (E3 dashboard writes via REST API)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS log_sources (
    id         BIGSERIAL    PRIMARY KEY,
    name       TEXT         NOT NULL,
    file_path  TEXT         NOT NULL UNIQUE,
    format     TEXT         NOT NULL DEFAULT 'auto',   -- 'syslog','nginx','json','auto'
    enabled    BOOLEAN      NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Pre-seed backend app logs
INSERT INTO log_sources (name, file_path, format) 
VALUES ('Main Backend App', '/app-logs/backend.log', 'json')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- events — parsed & normalised log events
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id         BIGSERIAL    PRIMARY KEY,
    source_id  BIGINT       REFERENCES log_sources(id) ON DELETE SET NULL,
    timestamp  TIMESTAMPTZ  NOT NULL,
    level      TEXT         NOT NULL DEFAULT 'INFO',   -- INFO, WARN, ERROR, CRITICAL
    source     TEXT         NOT NULL DEFAULT '',        -- hostname / application name
    message    TEXT         NOT NULL,
    raw        TEXT,                                    -- original raw log line
    metadata   JSONB        NOT NULL DEFAULT '{}',     -- extra parsed fields
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- rules — detection rules (E1 provides CRUD, E2 evaluator reads)
-- JSON condition schema:
--   { "type": "threshold"|"pattern"|"compound",
--     "field": "level"|"message"|...,
--     "pattern": "<regex>",
--     "threshold": <int>,
--     "window_seconds": <int>,
--     "operator": "AND"|"OR",
--     "conditions": [ ...nested... ] }
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rules (
    id          BIGSERIAL    PRIMARY KEY,
    name        TEXT         NOT NULL UNIQUE,
    description TEXT         NOT NULL DEFAULT '',
    condition   JSONB        NOT NULL,
    severity    TEXT         NOT NULL DEFAULT 'INFO',   -- INFO, WARN, CRITICAL
    action      JSONB        NOT NULL DEFAULT '{}',     -- {"notify_email":true,"webhook_url":"..."}
    enabled     BOOLEAN      NOT NULL DEFAULT true,
    version     INT          NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- alerts — generated by E2 rule-engine, read via E1 REST API
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alerts (
    id         BIGSERIAL    PRIMARY KEY,
    rule_id    BIGINT       REFERENCES rules(id)  ON DELETE SET NULL,
    event_id   BIGINT       REFERENCES events(id) ON DELETE SET NULL,
    severity   TEXT         NOT NULL,
    status     TEXT         NOT NULL DEFAULT 'open',    -- open, acknowledged, resolved
    message    TEXT         NOT NULL,
    metadata   JSONB        NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- raw_logs — staging table: collector inserts, parser reads & marks processed
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_logs (
    id         BIGSERIAL    PRIMARY KEY,
    source_id  BIGINT       REFERENCES log_sources(id) ON DELETE CASCADE,
    line       TEXT         NOT NULL,
    processed  BOOLEAN      NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_events_timestamp    ON events(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_level        ON events(level);
CREATE INDEX IF NOT EXISTS idx_events_source_id    ON events(source_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at   ON events(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_status       ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_severity     ON alerts(severity);
CREATE INDEX IF NOT EXISTS idx_alerts_rule_id      ON alerts(rule_id);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at   ON alerts(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_rules_enabled       ON rules(enabled) WHERE enabled;

CREATE INDEX IF NOT EXISTS idx_raw_logs_unprocessed ON raw_logs(processed) WHERE NOT processed;
