sonar.projectKey=tugas-ncc-irfansandy-backend
sonar.sources=backend,frontend
sonar.tests=backend,frontend
sonar.language=go

# Add ONLY the line matching the detected language:
sonar.go.coverage.reportPaths=backend/coverage.out
